import { expect, test } from 'bun:test'
import { mkdtempSync, readFileSync, rmSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'

const cli = new URL('./cli.ts', import.meta.url).pathname
const fixture = new URL('../tests/fixture.ts', import.meta.url).pathname

function run(cwd: string, ...args: string[]) {
	const result = Bun.spawnSync(['bun', cli, ...args], { cwd })
	return { code: result.exitCode, stderr: result.stderr.toString() }
}

test('stream-manifest writes deterministic modules, resolves lazy routers and checks staleness', () => {
	// Inside the repo so the router resolves the same @orpc/server copy.
	const dir = mkdtempSync(new URL('../.cli-test-', import.meta.url).pathname)
	try {
		writeFileSync(
			join(dir, 'router.ts'),
			`import { lazy } from '@orpc/server'
import { z } from 'zod'
import { fn, fnLive } from ${JSON.stringify(fixture)}
const feed = fnLive({
	name: 'feed',
	procedure: 'public',
	input: z.object({}),
	handler: () => 1,
	live: { eventSchema: z.object({}), channel: 'feed' }
})
const ping = fn({ name: 'ping', procedure: 'public', handler: () => 'pong' })
export const api = {
	ping,
	"it's": { subscribe: feed.subscribe },
	lazyFeed: lazy(async () => ({ default: { list: feed.procedure, watch: feed.subscribe } })),
	a: { subscribe: feed.subscribe }
}
// Open handle the CLI must not wait for.
setInterval(() => {}, 1000)
`
		)
		expect(
			run(dir, 'stream-manifest', 'router.ts#api', '--out', 'paths.ts')
		).toEqual({ code: 0, stderr: '' })
		expect(readFileSync(join(dir, 'paths.ts'), 'utf8')).toBe(
			`// Generated by \`orpc-fn stream-manifest\`. Do not edit.
export const streamPaths: readonly (readonly string[])[] = [
\t["a", "subscribe"],
\t["it's", "subscribe"],
\t["lazyFeed", "watch"]
]
`
		)
		expect(
			run(
				dir,
				'stream-manifest',
				'router.ts#api',
				'--out',
				'paths.ts',
				'--check'
			).code
		).toBe(0)

		writeFileSync(join(dir, 'paths.ts'), 'stale')
		const stale = run(
			dir,
			'stream-manifest',
			'router.ts#api',
			'--out',
			'paths.ts',
			'--check'
		)
		expect(stale.code).toBe(1)
		expect(stale.stderr).toContain('paths.ts is stale')
		expect(readFileSync(join(dir, 'paths.ts'), 'utf8')).toBe('stale')

		expect(
			run(dir, 'stream-manifest', 'router.ts#api', '--out', 'paths.json').code
		).toBe(0)
		expect(JSON.parse(readFileSync(join(dir, 'paths.json'), 'utf8'))).toEqual([
			['a', 'subscribe'],
			["it's", 'subscribe'],
			['lazyFeed', 'watch']
		])
		expect(
			run(dir, 'stream-manifest', 'router.ts#missing', '--out', 'x.ts').code
		).toBe(2)
		expect(run(dir, 'stream-manifest', 'router.ts').code).toBe(2)
	} finally {
		rmSync(dir, { recursive: true, force: true })
	}
})
