import {
	type AnyRouter,
	type AnyProcedure,
	resolveContractProcedures,
	traverseContractProcedures
} from '@orpc/server'
import { readFnMeta } from './meta.js'

/**
 * Creates a router object from routes or nested routers.
 * Simply returns the routes as a const object for type inference.
 *
 * @example
 * ```ts
 * const items = createRouter({ getItem, updateItem })
 * export const api = createRouter({ metabase, items })
 * ```
 */
export function createRouter<T extends AnyRouter>(routes: T): Readonly<T> {
	return routes
}

/** Serialize these paths to a frontend module; this helper belongs on the server. */
export function createStreamManifest(
	router: AnyRouter
): readonly (readonly string[])[] {
	const paths: string[][] = []
	const unresolved = traverseContractProcedures(
		{ router, path: [] },
		({ contract, path }) => {
			if (readFnMeta(contract as AnyProcedure).stream) paths.push([...path])
		}
	)
	if (unresolved.length)
		throw new TypeError(
			'orpc-fn: lazy routers require createStreamManifestAsync'
		)
	return paths
}

/** Resolve lazy routers before generating the same serializable path manifest. */
export async function createStreamManifestAsync(
	router: AnyRouter
): Promise<readonly (readonly string[])[]> {
	const paths: string[][] = []
	await resolveContractProcedures(
		{ router, path: [] },
		({ contract, path }) => {
			if (readFnMeta(contract as AnyProcedure).stream) paths.push([...path])
		}
	)
	return paths
}

/**
 * Deterministic module source for a stream manifest: paths sorted, `json`
 * as an array, `ts` as `export const <name>`. Used by `orpc-fn stream-manifest`.
 */
export function renderStreamManifest(
	paths: readonly (readonly string[])[],
	options: { format: 'json' | 'ts'; name?: string | undefined }
): string {
	const lines = paths
		.map(
			(path) =>
				`\t[${path.map((segment) => JSON.stringify(segment)).join(', ')}]`
		)
		.sort()
	const array = lines.length ? `[\n${lines.join(',\n')}\n]` : '[]'
	if (options.format === 'json') return `${array}\n`
	return `// Generated by \`orpc-fn stream-manifest\`. Do not edit.\nexport const ${options.name ?? 'streamPaths'}: readonly (readonly string[])[] = ${array}\n`
}
